### PR TITLE
Infer schema for items of .resources. Closes #3.

### LINKED ISSUE #3: Resource schemas
As discussed, infer resource schema:
- [x] if the remote does not have resource.schema
- [x] if the remote has resource.schema but this property is not a valid JSON table schema
- [x] if the resource is csv

### PR DESCRIPTION
**Pull request by gvidon**
Infer schema using https://www.npmjs.com/package/jts-infer for items of `.resources[]` which has mime type equal to `text/csv` and empty or non-object type `.schema`.

### CODE REVIEW

**Comment by pwalsh** [comment]
@gvidon why not json-table-schema-js?

**Comment by gvidon** [comment]
@pwalsh don't know why, but I missed that these are different packages. Will fix that.

**Comment by pwalsh** [comment]
@gvidon no worries. We definitely want json-table-schema-js to supersede jts-infer, and this will be a good chance to check the port you did.

**Comment by gvidon** [comment]
@pwalsh added `json-table-schema`

**Comment by pwalsh** [comment]
Please bump version (I just published): json-table-schema@0.0.2-alpha

**Comment by gvidon** [comment]
@pwalsh bumped `json-table-schema` version

**Pull request merged**
