### PR TITLE
Map remote (specified by URL) json into datapackage, tested.

### PR DESCRIPTION
**Pull request by gvidon**
- Currently maps CKAN v3 into base/tabular datapackage
- looks like there is no serious difference between base and tabular datapackages, so same mapping routine applied for both.

### CODE REVIEW

**Comment by gvidon** [comment]
In this version I don't generate `.schema` for each item from `.resources` of datapackage.

**Comment by pwalsh** [comment]
@gvidon read code, looks good, so I'm merging and creating on npm so you can work with it in DataPackagist. The schema generation is important though - you can use your new json-table-schema port for that :).

**Comment by gvidon** [comment]
@pwalsh how about generating schema of `.xls` files? From what I remember `json-table-schema` works with only csv?

**Comment by pwalsh** [comment]
@gvidon yes it only works with csv. in GoodTables, we open xls and then use it like a csv internally, and so there we can infer from xls. Here in the client - not so straight forward... Can you add a simple condition (and add comments so it is clear): if not CSV, schema is empty, otherwise run json-table-schema infer

**Comment by pwalsh** [comment]
@gvidon I see this but it could be a real pain in front end code (the File/Buffer thing): https://www.npmjs.com/package/xlsx

If we did have a nice way to do this, we could add it to the python lib too, so that this is possible even without GoodTables.

**Comment by gvidon** [comment]
@pwalsh ok, can add this improvement later.

**Comment by rufuspollock** [comment]
Aside: Note some stuff like this was in ckan.js library (though more focused on recline).

**Comment by pwalsh** [comment]
@rgrp thanks. I hadn't looked inside ckan.js, but I had checked out https://github.com/okfn/datapackage-ckan, which has a different purpose to what we are doing here.

**Pull request merged**
